export { default as Banner } from './banner/Banner';
export { default as Booking } from './booking/Booking';
export { default as Download } from './download/Download';
export { default as FAQ } from './FAQ/FAQ';
export { default as Home } from './home/Home';
export { default as Pick } from './pick/Pick';
export { default as Plan } from './plan/Plan';
export { default as WhyUs } from './whyUs/whyUs';
export { default as Testimonials } from './testimonials/Testimonials';